"""Regenerate Phase 1 tables from frozen evidence and independently re-scored PSNR."""
from __future__ import annotations

import argparse
import csv
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
METHODS = ["r3con-pano", "magician", "fisherrf", "gleam", "random", "gavis"]


def mean(values):
    values = list(values)
    return sum(values) / len(values)


def paired_rows(rows):
    index = {}
    for row in rows:
        key = (row["group"], row["scene"], row["method"], row["seed"], row["condition"])
        if key in index:
            raise ValueError(f"Duplicate cell {key}")
        index[key] = row
    pairs = []
    for key, static in index.items():
        if key[-1] != "d0":
            continue
        dynamic = index.get((*key[:-1], "dyn"))
        if dynamic is None:
            continue
        ds = dynamic["psnr_severe"] - static["psnr_severe"]
        dc = dynamic["psnr_clean"] - static["psnr_clean"]
        pairs.append(dict(group=key[0], scene=key[1], method=key[2], seed=key[3],
            static_severe=static["psnr_severe"], static_clean=static["psnr_clean"],
            delta_severe=ds, delta_clean=dc, regional_contrast=ds-dc,
            delta_overall=dynamic["psnr_shared"]-static["psnr_shared"],
            path_change_percent=100*(dynamic["path_length_m"] / static["path_length_m"] - 1),
            static_duration_s=static["actual_duration_s"], dynamic_duration_s=dynamic["actual_duration_s"]))
    return pairs


def csv_text(rows):
    f = io.StringIO(newline="")
    writer = csv.DictWriter(f, fieldnames=list(rows[0]), lineterminator="\n")
    writer.writeheader()
    writer.writerows(rows)
    return f.getvalue()


def build(root):
    campaign = json.loads((root / "campaign.json").read_text())
    rows, discrepancies = [], []
    for cell in campaign["cells"]:
        if cell["status"] != "retained":
            continue
        evidence = root / "evidence" / cell["id"]
        m = json.loads((evidence / "manifest.json").read_text())
        e = json.loads((evidence / "eval.json").read_text())
        verified = json.loads((root / "verification" / cell["id"] / "shared-legacy.json").read_text())
        if verified["n"] not in (39, 40, 80) or verified["color_mode"] != "legacy":
            raise ValueError(f"Unexpected evaluation regime: {cell['id']}")
        labels = verified["class_psnr"]
        if sum(labels[k]["n"] for k in ("severe", "clean")) != verified["n"]:
            raise ValueError(f"Incomplete evaluation partition: {cell['id']}")
        weighted = sum(labels[k]["psnr"]*labels[k]["n"] for k in ("severe", "clean")) / verified["n"]
        if abs(weighted-verified["psnr"]) > 1e-9:
            raise ValueError(f"Per-class/overall mismatch: {cell['id']}")
        cube = None
        if cell["group"] == "gs":
            cube = json.loads((root / "verification" / cell["id"] / "cube-legacy.json").read_text())["psnr"]
        row = dict(group=cell["group"], scene=cell["scene"], condition=cell["condition"],
            method=cell["method"], seed=cell["seed"], configured_budget_s=cell["configured_budget_s"],
            actual_duration_s=cell["actual_duration_s"], duration_status=cell["duration_status"],
            reconstruction_frames=cell["reconstruction_frames"], decision_captures=m["num_captures"],
            path_length_m=m["clock"]["path_length_m"], planning_wall_time_s=m["clock"]["planning_wall_time_s"],
            eval_views=verified["n"], n_severe=labels["severe"]["n"], n_clean=labels["clean"]["n"],
            psnr_shared=verified["psnr"], psnr_severe=labels["severe"]["psnr"], psnr_clean=labels["clean"]["psnr"],
            psnr_cube_provisional=cube, recorded_psnr_shared=cell["expected_psnr"],
            delta_from_recorded_db=verified["delta_from_recorded_db"], scoring="export_reload_legacy_dc",
            historical_completeness_5cm=e["geometry"]["completeness@0.05"],
            historical_ssim=e["appearance_per_stratum"]["all"]["ssim"],
            historical_lpips=e["appearance_per_stratum"]["all"]["lpips"])
        rows.append(row)
        if abs(row["delta_from_recorded_db"]) > 1e-5:
            discrepancies.append(dict(cell=cell["id"], recorded=cell["expected_psnr"],
                artifact_legacy=verified["psnr"], delta_db=verified["delta_from_recorded_db"],
                previous_color=cell["recorded_color_mode"], previous_scoring=cell["recorded_scoring_path"]))
    pairs = paired_rows(rows)
    lines = ["# ActiveBench Phase 1 results", "", "Generated by `python scripts/phase1/report.py`. All appearance PSNR below",
        "is independently re-scored from the exported models with legacy DC loading and all retained SH bands.",
        "The shared and provisional cube catalogs remain separate; no cross-group ranking is computed.", "",
        "| Group | Planned | Acquired | Standard models | At declared budget |", "|---|---:|---:|---:|---:|"]
    for group in ("mesh", "gs"):
        cs = [c for c in campaign["cells"] if c["group"] == group]
        lines.append(f"| {group} | {len(cs)} | {sum('actual_duration_s' in c for c in cs)} | {sum(c['status']=='retained' for c in cs)} | {sum(c.get('duration_status')=='complete' for c in cs)} |")
    lines += ["", "GS includes four 270 s GAVIS references and two shortened dynamic GLEAM runs.",
              "Mesh excludes two missing Skokloster GAVIS acquisitions and the two modified-recipe Van Gogh dynamic retries.", "",
              "## GS static means (two scenes, one acquisition seed)", "",
              "| Method | n | Shared PSNR | Cube PSNR, provisional | Planning wall time (s) |", "|---|---:|---:|---:|---:|"]
    for method in METHODS:
        subset = [r for r in rows if r["group"] == "gs" and r["condition"] == "d0" and r["method"] == method]
        lines.append(f"| {method} | {len(subset)}/2 | {mean(r['psnr_shared'] for r in subset):.2f} | {mean(r['psnr_cube_provisional'] for r in subset):.2f} | {mean(r['planning_wall_time_s'] for r in subset):.1f} |")
    lines += ["", "## Mesh static results (scene-wise)", "", "| Scene | Method | Shared PSNR |", "|---|---|---:|"]
    for row in rows:
        if row["group"] == "mesh" and row["condition"] == "d0":
            lines.append(f"| {row['scene']} | {row['method']} | {row['psnr_shared']:.2f} |")
    lines += ["", "## Regional dynamic-minus-static contrasts", "", "| Group | Scene | Method | Severe delta | Clean delta | Contrast |", "|---|---|---|---:|---:|---:|"]
    for p in pairs:
        lines.append(f"| {p['group']} | {p['scene']} | {p['method']} | {p['delta_severe']:+.3f} | {p['delta_clean']:+.3f} | {p['regional_contrast']:+.3f} |")
    mesh = [p for p in pairs if p["group"] == "mesh"]
    gs = [p for p in pairs if p["group"] == "gs" and p["method"] != "gleam"]
    lines += ["", f"Negative contrasts: mesh {sum(p['regional_contrast']<0 for p in mesh)}/{len(mesh)}; GS excluding GLEAM {sum(p['regional_contrast']<0 for p in gs)}/{len(gs)}.",
        "These are single-seed descriptive observations. Different acquired trajectories prevent a direct-occlusion causal interpretation.", "",
        "## Differences from historical scoring", "", "| Cell | Historical PSNR | Re-scored PSNR | Delta (dB) |", "|---|---:|---:|---:|"]
    for d in discrepancies:
        lines.append(f"| {d['cell']} | {d['recorded']:.6f} | {d['artifact_legacy']:.6f} | {d['delta_db']:+.6f} |")
    lines += ["", "Historical SSIM/LPIPS and geometric diagnostics in the CSV are named explicitly; this PSNR verification does not remeasure them.",
              "Full metric evaluation is available through `retrain_eval.py`. Models and original JSON remain unchanged.", ""]
    return {"results.csv": csv_text(rows), "pairs.csv": csv_text(pairs), "RESULTS.md": "\n".join(lines),
            "score-changes.json": json.dumps(discrepancies, indent=2) + "\n"}


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=ROOT / "phase1")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    outputs = build(args.root)
    for name, text in outputs.items():
        p = args.root / name
        if args.check:
            if not p.is_file() or p.read_text() != text:
                raise SystemExit(f"Stale generated table: {p}")
        else:
            p.write_text(text)
    print(f"{'Verified' if args.check else 'Generated'} {len(outputs)} files from primary evidence and model re-scores")
